Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "private_network", ip: "192.168.56.0"
    config.vm.provider "virtualbox" do |v|
        v.memory="2048"
        v.cpus="1"
    config.vm.provision "docker" do |d|    
     d.pull_images "rancher/rancher:latest"
    config.vm.provision "shell", inline:  "docker run -d --restart=unless-stopped \
        -p 80:80 -p 443:443 \
        --privileged \
        rancher/rancher:latest"
     end
   end
end