Vagrant.configure("2") do |vm2|
    vm2.vm.box = "ubuntu/xenial64"
    vm2.vm.network "private_network", ip: "192.168.56.3"
    vm2.vm.provider "virtualbox" do |v|
        v.memory="2048"
        v.cpus="1"
   end
end
