Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    
    config.vm.define "machine1" do |machine1|
        machine1.vm.network "private_network", ip: "192.168.56.10"
        machine1.vm.provider "virtualbox" do |v|
            v.memory="4096"
            v.cpus="2"
        end
    end
    config.vm.define "machine2" do |machine2|
        machine2.vm.network "private_network", ip: "192.168.56.11" 
        machine2.vm.provider "virtualbox" do |v|
            v.memory="4096"
            v.cpus="2"
        end
    end
    config.vm.define "rancher" do |rancher|
        rancher.vm.network "private_network", ip: "192.168.56.12" 
        rancher.vm.provider "virtualbox" do |v|
            v.memory="4096"
            v.cpus="2"
        end
    end
end
