Vagrant.configure("2") do |vm1|
    vm1.vm.box = "ubuntu/xenial64"
    vm1.vm.network "private_network", ip: "192.168.56.2"
    vm1.vm.provider "virtualbox" do |v|
        v.memory="2048"
        v.cpus="1"
   end
end